baseURL = "https://www.debyez.com/"
languageCode = "en-us"
title = "Debyez"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""
  background = 'images/fighter-jet.jpg'

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "40px"
    desktop_width = "160px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Debyez is a software company providing cutting-edge AI solutions for S1000D Authoring and publication"
    meta_og_title = "Debyez"
    meta_og_type = "website"
    meta_og_url = "https://www.debyez.com"
    meta_og_description ="Debyez is a software company providing cutting-edge AI solutions for S1000D Authoring and publication"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
